apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{ image }}
  port: 8092
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 3
    max: 3
  kafka:
    pool: nav-prod
  resources:
    limits:
      memory: 2024Mi
    requests:
      cpu: 800m
      memory: 1024Mi
  ingresses:
    - "https://dp-regel-api.nais.adeo.no"
  secureLogs:
    enabled: true
  vault:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dp-kalkulator-api
          namespace: teamdagpenger
          cluster: prod-gcp
        - application: dp-regel-api-arena-adapter
        - application: dp-proxy

  # required for on-premises only
  webproxy: true