apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: "{{app}}"
  namespace: "{{namespace}}"
  labels:
    team: "{{team}}"
spec:
  image: "{{ image }}"
  port: 8092
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 3
    max: 3
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 384Mi
  kafka:
    pool: nav-dev
  ingresses:
    - https://dp-regel-api.intern.dev.nav.no
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dp-mottak
        - application: dp-regel-api-arena-adapter
          namespace: teamdagpenger
          cluster: dev-fss
        - application: dp-proxy
          namespace: teamdagpenger
          cluster: dev-fss
  env:
    - name: JDK_JAVA_OPTIONS
      value: -XX:+UseParallelGC -XX:MaxRAMPercentage=35.0 -XX:ActiveProcessorCount=4
  gcp:
    sqlInstances:
      - collation: nb_NO.UTF8
        databases:
          - envVarPrefix: DB
            name: regel
        diskAutoresize: true
        diskType: SSD
        highAvailability: false
        insights:
          enabled: true
          queryStringLength: 4500
          recordApplicationTags: true
          recordClientAddress: true
        maintenance:
          day: 1
          hour: 4
        pointInTimeRecovery: false
        tier:	db-custom-1-3840
        flags:
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: 'write'
        type: POSTGRES_15
