name: Build and deploy

on: [ push ]

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v3.5.0
        with:
          arguments: check build
      - uses: nais/docker-build-push@v0
        name: docker-build-push
        id: docker-build-push
        with:
          team: teamdagpenger
          tag: latest
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-dev:
    name: Deploy to dev
    needs: [build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: dev-gcp
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/dev/nais.yaml
          VARS: nais/vars.yaml
          VAR: image=${{ needs.build.outputs.image }}
          PRINT_PAYLOAD: true
  deploy-prod:
    name: Deploy to Production
    needs: [build, deploy-dev]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod-gcp
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/prod/nais.yaml
          VARS: nais/vars.yaml
          VAR: image=${{ needs.build.outputs.image }}
          PRINT_PAYLOAD: true
